language: node_js
node_js:
- '0.10'
env:
  global:
  - secure: iTkBBacRgTB2dwvf9QLMlthkbxbqtndJ9+5KD1Rg6Sq3XYqRocx9xXzod2LKOBHZtyQzwwMFLan7ns4xDRt46kJ0n6SDDajtoB4ix97eRz2JXDy1+4uTCrgVI7wVNQ0tgElJRsOWPszLbXoqtZwh0HuWNEgFBxD+q5eWtJmlDGc=
  - secure: fZiKlJfc0D/V8/FWrurT6QKmH6AHq2XSIAzZWKLH39SLa2XE68+71wojrjVJ8vfMKrJ+ejaHpIdTjFSb/8FANuLn5dDYDbb7YIsk97z6Qi1ZmNg1qrBDXMjh2ygUzt/Wf04FFi3QwtRo6o2jZYdBGGlFlNJguVrBvFRkZgVbayg=
  matrix:
  - BROWSER_NAME=chrome BROWSER_VERSION=latest
  - BROWSER_NAME=chrome BROWSER_VERSION=35
  - BROWSER_NAME=chrome BROWSER_VERSION=34
  - BROWSER_NAME=firefox BROWSER_VERSION=latest
  - BROWSER_NAME=firefox BROWSER_VERSION=30
  - BROWSER_NAME=firefox BROWSER_VERSION=29
  - BROWSER_NAME=opera BROWSER_VERSION=latest
  - BROWSER_NAME=opera BROWSER_VERSION=11
  - BROWSER_NAME=safari BROWSER_VERSION=latest
  - BROWSER_NAME=safari BROWSER_VERSION=7
  - BROWSER_NAME=safari BROWSER_VERSION=6
  - BROWSER_NAME=safari BROWSER_VERSION=5
  - BROWSER_NAME=ie BROWSER_VERSION=11
  - BROWSER_NAME=ie BROWSER_VERSION=10
  - BROWSER_NAME=ie BROWSER_VERSION=9
  - BROWSER_NAME=iphone BROWSER_VERSION=7.1
  - BROWSER_NAME=iphone BROWSER_VERSION=7.0
  - BROWSER_NAME=iphone BROWSER_VERSION=6.1
